
repos:
  - repo: local
    hooks:
      # - id: pytest
      #   name: Run tests
      #   entry: uv run pytest
      #   language: python
      #   types: [python]
      #   pass_filenames: false
      #   always_run: true
      - id: ruff sort
        name: Ruff linter
        entry: uv run ruff format .
        language: python
        types_or: [python, pyi]
      - id: ruff sort
        name: Run ruff linter
        entry: uv run ruff check --select I --fix .
        language: python
        types_or: [python, pyi]
        pass_filenames: true
